services:
    vert:
        container_name: vert
        image: z8-work:local
        build:
            context: .
            args:
                PUB_HOSTNAME: ${PUB_HOSTNAME:-z8.work}
                PUB_PLAUSIBLE_URL: ${PUB_PLAUSIBLE_URL:-}
                PUB_ENV: ${PUB_ENV:-production}
                PUB_DISABLE_ALL_EXTERNAL_REQUESTS: ${PUB_DISABLE_ALL_EXTERNAL_REQUESTS:-false}
                PUB_VERTD_URL: ${PUB_VERTD_URL:-}
        restart: unless-stopped
        ports:
            - ${PORT:-3000}:80
