FROM z8-phase28-core24-lcms:local
RUN apt-get update && apt-get install -y --no-install-recommends python3 libfreetype-dev libgumbo-dev libharfbuzz-dev libjbig2dec0-dev libmujs-dev libopenjp2-7-dev zlib1g-dev
