// Build and validation inputs, shared by the receipt and CI coverage check.
// This is an explicit source allowlist, not a recursive working-directory archive.
export const inputPaths = [
	"desktop",
	"src",
	"src-tauri",
	"scripts",
	"tests",
	"packaging/desktop",
	"static/desktop-info",
	"package.json",
	"bun.lock",
	"LICENSE",
	"postcss.config.js",
	"tailwind.config.ts",
	"tsconfig.json",
	"svelte.config.js",
	"rust-toolchain.toml",
	"eslint.config.js",
	".prettierrc",
	".prettierignore",
	".gitignore",
	".gitattributes",
	".github/workflows/desktop.yml",
];
